"""Tag repository interface."""

from __future__ import annotations

from typing import Protocol

from docflow.domain.entities import Tag


class TagRepository(Protocol):
    def add(self, tag: Tag) -> Tag: ...
    def get(self, tag_id: int) -> Tag: ...
    def list_all(self) -> list[Tag]: ...
    def update(self, tag: Tag) -> None: ...
    def delete(self, tag_id: int) -> None: ...
    def list_for_document(self, document_id: int) -> list[Tag]: ...
    def attach(self, document_id: int, tag_id: int) -> None: ...
    def detach(self, document_id: int, tag_id: int) -> None: ...
    def count_documents(self, tag_id: int) -> int: ...
