"""Version and Branch repository interface."""

from __future__ import annotations

from typing import Protocol

from docflow.domain.entities import Branch, DocumentVersion


class VersionRepository(Protocol):
    # --- Branches ---
    def add_branch(self, branch: Branch) -> Branch: ...
    def list_branches(self, document_id: int) -> list[Branch]: ...
    def get_branch(self, branch_id: int) -> Branch: ...
    def set_head(self, branch_id: int, version_id: int) -> None: ...

    # --- Versions ---
    def add_version(self, version: DocumentVersion) -> DocumentVersion: ...
    def get_version(self, version_id: int) -> DocumentVersion: ...
    def list_versions(self, document_id: int) -> list[DocumentVersion]:
        """All versions across all branches, ordered by created_at desc."""
        ...

    def list_versions_in_branch(self, branch_id: int) -> list[DocumentVersion]: ...
    def get_head(self, document_id: int, branch_name: str = "main") -> DocumentVersion | None: ...
